version: '2'
services:
  app:
    image: 'task-schedueler-spring-boot-postgres:latest'
    expose:
      - 8080
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app
    depends_on:
       - db
    environment:
      - POSTGRES_PASSWORD=sample
      - POSTGRES_USER=sample
      - POSTGRES_DB=sample
      - PGDATA=/var/lib/postgresql/data/pgdata
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    container_name: sample_db
    image: postgres:13
    volumes:
      - sample_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=sample
      - POSTGRES_USER=sample
      - POSTGRES_DB=sample
      - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
      - 5432
    ports:
      - 5432:5432
volumes:
  sample_db: {}